name: 'Deploy'
on:
  push:
    branches: [ main ]
pull_request:

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: No going back now
        run: echo "I am deploying"
#      - name: Fail
#        run: exit 1